# Generated by Django 4.1 on 2023-04-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('loan_type', models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('enterprise', 'ENTERPRISE')], default='small', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='LoanPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Enter Firstname', max_length=15, verbose_name='Firstname')),
                ('lastname', models.CharField(help_text='Enter Lastname', max_length=15, verbose_name='Lastname')),
                ('dependants', models.IntegerField(help_text='Enter Number of Dependents', verbose_name='Dependants')),
                ('applicant_income', models.IntegerField(help_text='Enter Monthly Gross Income in Dollars', verbose_name='Income')),
                ('co_applicant_income', models.IntegerField(help_text='Enter Monthly Gross Income in Dollars', verbose_name='Co-Income')),
                ('loan_amt', models.IntegerField(help_text='Requested Loan Amount in Dollars', verbose_name='Loan Amount')),
                ('loan_term', models.IntegerField(help_text='Loan Term in Months', verbose_name='Loan Term')),
                ('credit_history', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=4, verbose_name='Credit Histroy')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, verbose_name='Gender')),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, verbose_name='Marital Status')),
                ('graduate', models.CharField(choices=[('Graduate', 'Graduated'), ('Not Graduate', 'Not Graduate')], max_length=15, verbose_name='Education Status')),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, verbose_name='Employment Status')),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15, verbose_name='Area Status')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_loan', to='main.loan')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_service', to='main.service')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
