# Generated by Django 4.1 on 2023-03-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='text',
        ),
    ]
