# Generated by Django 4.1 on 2023-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('file_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=15, verbose_name='Lastname')),
                ('dependants', models.IntegerField(default=0, verbose_name='Dependants')),
                ('applicant_income', models.IntegerField(default=0, verbose_name='Income')),
                ('co_applicant_income', models.IntegerField(default=0, verbose_name='Co-Income')),
                ('loan_amt', models.IntegerField(default=0, verbose_name='Loan Amount')),
                ('loan_term', models.IntegerField(default=0, verbose_name='Loan Term')),
                ('credit_history', models.IntegerField(default=0, verbose_name='Credit Histroy')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, verbose_name='Gender')),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, verbose_name='Marital Status')),
                ('graduate', models.CharField(choices=[('Graduate', 'Graduated'), ('Not Graduate', 'Not Graduate')], max_length=15, verbose_name='Education Status')),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, verbose_name='Employment Status')),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15, verbose_name='Area Status')),
            ],
        ),
    ]
