# Generated by Django 4.1 on 2023-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_file_loanpred'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_location',
            field=models.CharField(default='location', max_length=100),
        ),
    ]
