# Generated by Django 4.1 on 2023-03-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_description_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
