# Generated by Django 4.1 on 2023-04-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_file_file_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_location',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
    ]
